/* eslint-disable */
/**
 * STUB FILE - This file will be auto-generated when you run `npx convex dev`
 *
 * This stub allows TypeScript compilation to succeed before Convex is initialized.
 * DO NOT edit this file manually - it will be overwritten.
 */

export type Id<TableName extends string> = string & { __tableName: TableName };

export type Doc<TableName extends string> = {
  _id: Id<TableName>;
  _creationTime: number;
} & Record<string, any>;

// Stub table names
export type TableNames =
  | "companies"
  | "contacts"
  | "callRecords"
  | "contactNotes"
  | "syncMetadata"
  | "dailyStats";

export type DataModel = {
  companies: Doc<"companies">;
  contacts: Doc<"contacts">;
  callRecords: Doc<"callRecords">;
  contactNotes: Doc<"contactNotes">;
  syncMetadata: Doc<"syncMetadata">;
  dailyStats: Doc<"dailyStats">;
};
