/* eslint-disable */
/**
 * STUB FILE - This file will be auto-generated when you run `npx convex dev`
 *
 * This stub allows TypeScript compilation to succeed before Convex is initialized.
 * DO NOT edit this file manually - it will be overwritten.
 */

export const query = (() => {}) as any;
export const mutation = (() => {}) as any;
export const action = (() => {}) as any;
export const internalQuery = (() => {}) as any;
export const internalMutation = (() => {}) as any;
export const internalAction = (() => {}) as any;
